In [143]:
import pandas as pd
import numpy as np
import json
import ast
import random
from sklearn.neighbors import NearestNeighbors
from sklearn.metrics import mean_squared_error
from sklearn.metrics import ndcg_score

In [2]:
dataset = pd.read_csv("dataset/okcupid_profile_data.csv")
dataset.insert(0, 'ID', range(0, len(dataset)))
dataset = dataset.head(5000)

group_counts = dataset.groupby(['orientation', 'sex']).size()
print(group_counts)
# dataset['sex'].unique()

orientation  sex
bisexual     f        96
             m        32
gay          f        68
             m       189
straight     f      1810
             m      2805
dtype: int64


In [3]:
comp_scores = "dataset/compatibility_5k.json"
with open(comp_scores) as f:
    comp_scores = json.loads(f.read())

def get_dict(row):
    index = [random.randint(0, 9999) for _ in range(50)]
    score = [random.random() for _ in range(50)]
    return comp_scores.get(str(row['ID']), {'index':index, 'score':score})

# Adding new column with corresponding dictionary
dataset['top_compatible'] = dataset.apply(get_dict, axis=1)
test_dataset = dataset[dataset['top_compatible'] != {}]
len(test_dataset)

5000

In [5]:
og_rating_matrix = np.zeros((len(test_dataset),len(test_dataset)))
rating_matrix = np.zeros((len(test_dataset),len(test_dataset)))

In [6]:
# Populate the ORIGINAL compatibility matrix
for idx, row in test_dataset.iterrows():
    user_id = row['ID']
    compatibilities = row['top_compatible']
    
    for compatible_id, score in zip(compatibilities['index'], compatibilities['score']):
        og_rating_matrix[user_id][compatible_id] = score
        og_rating_matrix[compatible_id][user_id] = score

for i in range(len(test_dataset)):
    og_rating_matrix[i][i] = 0

print(og_rating_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [7]:
# Populate the compatibility matrix TO USE
for idx, row in test_dataset.iterrows():
    user_id = row['ID']
    compatibilities = row['top_compatible']
    
    for compatible_id, score in zip(compatibilities['index'][:10], compatibilities['score'][:10]):
        rating_matrix[user_id][compatible_id] = score
        rating_matrix[compatible_id][user_id] = score

for i in range(len(test_dataset)):
    rating_matrix[i][i] = 0

print(rating_matrix)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
def predict_ratings(user_item_matrix, target_user_index, X, n_neighbors=20, n_recommendations=10):
    """
    Predict ratings for all items for a specific user using a modified k-NN approach
    that excludes the first X closest neighbors.

    Parameters:
    - user_item_matrix: 2D numpy array with rows as users and columns as items. Cell values are ratings.
    - target_user_index: Index of the target user for whom we want to predict ratings.
    - X: Number of closest neighbors to exclude.
    - n_neighbors: Number of neighbors to consider for prediction after excluding the first X.

    Returns:
    - predicted_ratings: A numpy array with the predicted ratings for each item.
    """
    
    # Ensure n_neighbors is less than the number of users minus the ones we skip
    total_users = user_item_matrix.shape[0]
    if n_neighbors + X >= total_users:
        raise ValueError("n_neighbors + X must be less than the total number of users.")

    # Initialize NearestNeighbors
    nbrs = NearestNeighbors(n_neighbors=n_neighbors+X+1, metric='euclidean')
    nbrs.fit(user_item_matrix)

    # Find the nearest neighbors (including the user itself)
    distances, indices = nbrs.kneighbors(user_item_matrix[target_user_index].reshape(1, -1))
    # print(distances, indices)
    if(n_neighbors + X > len(indices[0])):
        print(f"could not find enough neighbours... only {len(indices[0])} could be found :(")
        return
    
    # Exclude the first X+1 closest neighbors to skip the user itself and the X closest neighbors
    relevant_indices = indices.flatten()[X+1:]
    relevant_distances = distances.flatten()[X+1:]
    # print("relevant_indices: ", relevant_indices)
    # print("relevant_distances: ", relevant_distances)
    
    # Initialize predictions array with zeros
    predicted_ratings = np.zeros(user_item_matrix.shape[1])
    
    # Calculate predictions for each item
    for item_index in range(user_item_matrix.shape[1]):
        # Skip if the user has already rated this item
        if user_item_matrix[target_user_index, item_index] > 0:
            continue
    
        # Aggregate ratings from neighbors for this item
        total_rating = 0
        total_weight = 0
        for i,neighbor_index in enumerate(relevant_indices):
            neighbor_rating = user_item_matrix[neighbor_index, item_index]
            if neighbor_rating > 0:
                # Use inverse distance as weight, add a small epsilon to avoid division by zero
                # print(i, neighbor_index, len(relevant_distances))
                weight = 1 / (relevant_distances[i] + 1e-5)
                total_rating += neighbor_rating * weight
                total_weight += weight
    
        # Predict rating if there are neighbors who rated this item
        if total_weight > 0:
            predicted_ratings[item_index] = total_rating / total_weight

    recommendations = {}

    for i,rating in enumerate(predicted_ratings):
        if(rating > 0):
            recommendations[i] = rating
    
    top_recommendations = dict(sorted(recommendations.items(), key=lambda item: item[1], reverse=True)[:n_recommendations])

    return top_recommendations

In [32]:
# 20 neighbours
results_serendipity = {}
for i in range(len(test_dataset)):
    results_serendipity[i] = predict_ratings(rating_matrix, i, 10, 30, 20) #with serendipity

results_serendipity_df = pd.DataFrame(results_serendipity.items(), columns=['ID', 'scores_with_serendipity'])
results_serendipity_df.head()

results_wo_serendipity = {}
for i in range(len(test_dataset)):
    results_wo_serendipity[i] = predict_ratings(rating_matrix, i, 0, 20, 20) #without serendipity

results_wo_serendipity_df = pd.DataFrame(results_wo_serendipity.items(), columns=['ID', 'scores_without_serendipity'])
results_wo_serendipity_df.head()

ID                                             scores
0   0  {3326: 0.3785120093869527, 819: 0.374539781532...
1   1  {3468: 0.40364603521503745, 2989: 0.4028731378...
2   2  {4342: 0.3767480246888364, 2213: 0.37569636824...
3   3  {4448: 0.36025621693398535, 3245: 0.3547693906...
4   4  {1254: 0.38124031124909735, 3176: 0.3803370972...

In [187]:
# 5 neighbours
results_serendipity = {}
for i in range(len(test_dataset)):
    results_serendipity[i] = predict_ratings(rating_matrix, i, 10, 15, 20) #with serendipity

results_serendipity_df = pd.DataFrame(results_serendipity.items(), columns=['ID', 'scores_with_serendipity'])
results_serendipity_df.head()

results_wo_serendipity = {}
for i in range(len(test_dataset)):
    results_wo_serendipity[i] = predict_ratings(rating_matrix, i, 0, 5, 20) #without serendipity

results_wo_serendipity_df = pd.DataFrame(results_wo_serendipity.items(), columns=['ID', 'scores_without_serendipity'])
results_wo_serendipity_df.head()

write_to_csv(5)

In [188]:
# 10 neighbours
results_serendipity = {}
for i in range(len(test_dataset)):
    results_serendipity[i] = predict_ratings(rating_matrix, i, 10, 20, 20) #with serendipity

results_serendipity_df = pd.DataFrame(results_serendipity.items(), columns=['ID', 'scores_with_serendipity'])
results_serendipity_df.head()

results_wo_serendipity = {}
for i in range(len(test_dataset)):
    results_wo_serendipity[i] = predict_ratings(rating_matrix, i, 0, 10, 20) #without serendipity

results_wo_serendipity_df = pd.DataFrame(results_wo_serendipity.items(), columns=['ID', 'scores_without_serendipity'])
results_wo_serendipity_df.head()

write_to_csv(10)

In [189]:
# 25 neighbours
results_serendipity = {}
for i in range(len(test_dataset)):
    results_serendipity[i] = predict_ratings(rating_matrix, i, 10, 35, 20) #with serendipity

results_serendipity_df = pd.DataFrame(results_serendipity.items(), columns=['ID', 'scores_with_serendipity'])
results_serendipity_df.head()

results_wo_serendipity = {}
for i in range(len(test_dataset)):
    results_wo_serendipity[i] = predict_ratings(rating_matrix, i, 0, 25, 20) #without serendipity

results_wo_serendipity_df = pd.DataFrame(results_wo_serendipity.items(), columns=['ID', 'scores_without_serendipity'])
results_wo_serendipity_df.head()

write_to_csv(25)

In [186]:
def write_to_csv(no_neighbours):
    rows = []
    for key, value in comp_scores.items():
        row = {'ID': int(key)}
        index_score_dict = {idx: score for idx, score in zip(value['index'], value['score'])}
        row['Original_Compatibility_Scores'] = index_score_dict
        rows.append(row)
    
    # Create DataFrame
    original_score_df = pd.DataFrame(rows)
    merged_df = results_serendipity_df.merge(results_wo_serendipity_df, on='ID')
    merged_df = merged_df.merge(original_score_df, on='ID')
    file_name = f"dataset/recommendations_all_k{str(no_neighbours)}.csv"
    merged_df.to_csv(file_name, index=False)

In [183]:
write_to_csv(5)

In [237]:
no_neighbours = 20
file_name = f"dataset/recommendations_all_k{str(no_neighbours)}.csv"
scores_df = pd.read_csv(file_name)
org_score, pred_spty, pred_wo_spty = 0, 0, 0
for row in scores_df.itertuples():
    original_scores = ast.literal_eval(row.Original_Compatibility_Scores)
    predicted_scores_spty = ast.literal_eval(row.scores_with_serendipity)
    predicted_scored_wo_spty = ast.literal_eval(row.scores_without_serendipity)
    if len(original_scores) < 40:
        org_score += 1
    if len(predicted_scores_spty) < 20:
        pred_spty += 1
    if len(predicted_scored_wo_spty) < 20:
        pred_wo_spty += 1
print(org_score, pred_spty, pred_wo_spty)
scores_df.head()
# scores_df.columns

0 0 5


ID                            scores_with_serendipity  \
0   0  {3326: 0.3785120093869527, 819: 0.374539781532...   
1   1  {3468: 0.40364603521503745, 2989: 0.4028731378...   
2   2  {4342: 0.3767480246888364, 2213: 0.37569636824...   
3   3  {4448: 0.36025621693398535, 3245: 0.3547693906...   
4   4  {1254: 0.38124031124909735, 3176: 0.3803370972...   

                          scores_without_serendipity  \
0  {3917: 0.38406434084614316, 3185: 0.3824058831...   
1  {2857: 0.37889702227935546, 2409: 0.3774439090...   
2  {347: 0.37504157037857033, 1597: 0.37298791244...   
3  {381: 0.3875333601955412, 1828: 0.386575334678...   
4  {2560: 0.3812612864740654, 1254: 0.38124031124...   

                       Original_Compatibility_Scores  
0  {3916: 0.404574517131177, 786: 0.4005645957215...  
1  {896: 0.40955449736165245, 2127: 0.40863726632...  
2  {4264: 0.4048764780749057, 4745: 0.40487647807...  
3  {1827: 0.36888572989623986, 4930: 0.3652856970...  
4  {2328: 0.40846110821772325, 2261: 0.4084468473...

In [230]:
def calc_rmse(scores_df, no_of_recs):
    mse_values_spty = []
    mse_values_wo_spty = []
    for row in scores_df.itertuples():
        original_scores = ast.literal_eval(row.Original_Compatibility_Scores)
        predicted_scores_spty = ast.literal_eval(row.scores_with_serendipity)
        predicted_scored_wo_spty = ast.literal_eval(row.scores_without_serendipity)
        squared_diff_sum_spty = 0
        squared_diff_sum_wo_spty = 0
        for id, predict in predicted_scores_spty.items():
            original_score = original_scores.get(id, 0.0)
            squared_diff_sum_spty += (predict - original_score) ** 2

        for id, predict in predicted_scored_wo_spty.items():
            original_score = original_scores.get(id, 0.0)
            squared_diff_sum_wo_spty += (predict - original_score) ** 2
        
        mse_spty = squared_diff_sum_spty / no_of_recs
        mse_values_spty.append(mse_spty)

        mse_wo_spty = squared_diff_sum_wo_spty / no_of_recs
        mse_values_wo_spty.append(mse_wo_spty)
    
    # Calculate average RMSE
    average_rmse_spty = np.sqrt(np.mean(mse_values_spty))
    average_rmse_wo_spty = np.sqrt(np.mean(mse_values_wo_spty))
    
    # print("RMSE values with serendipity:", rmse_values_spty)
    # print("RMSE values without serendipity:", rmse_values_wo_spty)
    # print("Average RMSE with serendipity:", average_rmse_spty)
    # print("Average RMSE without serendipity:", average_rmse_wo_spty)
    return average_rmse_spty, average_rmse_wo_spty

In [231]:
rmse_spty, rmse_wo_spty = calc_rmse(scores_df, 20)
print("RMSE with serendipity = ", rmse_spty)
print("RMSE without serendipity = ",rmse_wo_spty)

RMSE with serendipity =  0.2757859597632517
RMSE without serendipity =  0.265034329036201


In [232]:
def calc_ndcg_at_k(scores_df, k):
    ndcg_spty = []
    ndcg_wo_spty = []
    for row in scores_df.itertuples():
        original_scores = ast.literal_eval(row.Original_Compatibility_Scores)
        predicted_scores_spty = ast.literal_eval(row.scores_with_serendipity)
        predicted_scored_wo_spty = ast.literal_eval(row.scores_without_serendipity)
        # print(original_scores)
        # print(predicted_scores_spty)
        # print(predicted_scored_wo_spty)
        row_scores_act_spty = []
        row_scores_act_wo_spty = []
        for id, predict in predicted_scores_spty.items():
            original_score = original_scores.get(id, 0.0)
            row_scores_act_spty.append(original_score)
        
        for id, predict in predicted_scored_wo_spty.items():
            original_score = original_scores.get(id, 0.0)
            row_scores_act_wo_spty.append(original_score)

        row_scores_act_spty = row_scores_act_spty[:k]
        row_score_true_spty = sorted(row_scores_act_spty, reverse=True)
        # print(row_scores_act_spty)
        # print(row_score_true_spty)

        row_scores_act_wo_spty = row_scores_act_wo_spty[:k]
        row_score_true_wo_spty = sorted(row_scores_act_wo_spty, reverse=True)
        # print(row_scores_act_wo_spty)
        # print(row_score_true_wo_spty)

        row_ndcg_spty = ndcg_score(np.asarray([row_score_true_spty]), np.asarray([row_scores_act_spty]))
        row_ndcg_wo_spty = ndcg_score(np.asarray([row_score_true_wo_spty]), np.asarray([row_scores_act_wo_spty]))

        ndcg_spty.append(row_ndcg_spty)
        ndcg_wo_spty.append(row_ndcg_wo_spty)

    average_ndcg_spty = np.mean(ndcg_spty) 
    average_ndcg_wo_spty = np.mean(ndcg_wo_spty)

    return average_ndcg_spty, average_ndcg_wo_spty


In [233]:
# new_df = scores_df.head()
ndcg_spty, ndcg_wo_spty = calc_ndcg_at_k(scores_df, 5)
print("Print ndcg@5 with serendipity =", ndcg_spty)
print("Print ndcg@5 without serendipity  =", ndcg_wo_spty)

ndcg_spty, ndcg_wo_spty = calc_ndcg_at_k(scores_df, 10)
print("Print ndcg@10 with serendipity  =", ndcg_spty)
print("Print ndcg@10 without serendipity  =", ndcg_wo_spty)

ndcg_spty, ndcg_wo_spty = calc_ndcg_at_k(scores_df, 15)
print("Print ndcg@15 with serendipity  =", ndcg_spty)
print("Print ndcg@15 without serendipity  =", ndcg_wo_spty)

ndcg_spty, ndcg_wo_spty = calc_ndcg_at_k(scores_df, 20)
print("Print ndcg@20 with serendipity  =", ndcg_spty)
print("Print ndcg@20 without serendipity  =", ndcg_wo_spty)

Print ndcg@5 with serendipity = 0.6942066722330584
Print ndcg@5 without serendipity  = 0.7654898189561443
Print ndcg@10 with serendipity  = 0.7040279691148403
Print ndcg@10 without serendipity  = 0.7710778280023518
Print ndcg@15 with serendipity  = 0.6982248663359311
Print ndcg@15 without serendipity  = 0.761678497465735
Print ndcg@20 with serendipity  = 0.6923264564998994
Print ndcg@20 without serendipity  = 0.7529606434052036


In [234]:
def calc_precision_at_k(scores_df, k):
    prec_spty = []
    prec_wo_spty = []
    for row in scores_df.itertuples():
        original_scores = ast.literal_eval(row.Original_Compatibility_Scores)
        predicted_scores_spty = ast.literal_eval(row.scores_with_serendipity)
        predicted_scored_wo_spty = ast.literal_eval(row.scores_without_serendipity)
        # print(original_scores)
        # print(predicted_scores_spty)
        # print(predicted_scored_wo_spty)
        row_prec_spty = []
        row_prec_wo_spty = []
        for id, predict in predicted_scores_spty.items():
            original_score = original_scores.get(id, 0)
            row_prec_spty.append(original_score)
        
        for id, predict in predicted_scored_wo_spty.items():
            original_score = original_scores.get(id, 0)
            row_prec_wo_spty.append(original_score)

        row_prec_spty = row_prec_spty[:k]
        row_prec_spty = [1 if k > 0 else 0 for k in row_prec_spty]
        row_prec_spty = sum(row_prec_spty)/k
        # print(row_prec_spty)
        # print(row_score_true_spty)

        row_prec_wo_spty = row_prec_wo_spty[:k]
        row_prec_wo_spty = [1 if k > 0 else 0 for k in row_prec_wo_spty]
        row_prec_wo_spty = sum(row_prec_wo_spty)/k
        # print(row_prec_wo_spty)
        # print(row_score_true_wo_spty)

        prec_spty.append(row_prec_spty)
        prec_wo_spty.append(row_prec_wo_spty)

    average_prec_spty = np.mean(prec_spty) 
    average_prec_wo_spty = np.mean(prec_wo_spty)

    return average_prec_spty, average_prec_wo_spty


In [235]:
# new_df = scores_df.head()
prec_spty, prec_wo_spty = calc_precision_at_k(scores_df, 5)
print("Print prec@5 with serendipity =", prec_spty)
print("Print prec@5 without serendipity  =", prec_wo_spty)

prec_spty, prec_wo_spty = calc_precision_at_k(scores_df, 10)
print("Print prec@10 with serendipity  =", prec_spty)
print("Print prec@10 without serendipity  =", prec_wo_spty)

prec_spty, prec_wo_spty = calc_precision_at_k(scores_df, 15)
print("Print prec@15 with serendipity  =", prec_spty)
print("Print prec@15 without serendipity  =", prec_wo_spty)

prec_spty, prec_wo_spty = calc_precision_at_k(scores_df, 20)
print("Print prec@20 with serendipity  =", prec_spty)
print("Print prec@20 without serendipity  =", prec_wo_spty)

Print prec@5 with serendipity = 0.50388
Print prec@5 without serendipity  = 0.58116
Print prec@10 with serendipity  = 0.45498
Print prec@10 without serendipity  = 0.5241399999999999
Print prec@15 with serendipity  = 0.40954666666666667
Print prec@15 without serendipity  = 0.46588
Print prec@20 with serendipity  = 0.37051000000000006
Print prec@20 without serendipity  = 0.4154
